version: '3.8'

services:
  mysql-database:
    image: mysql
    container_name: my-mysql-container
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
