version: '3.8'

services:
  app-backend:
    build: .
    container_name: app-php-backend
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    stdin_open: true
    tty: true

  mysql:
    image: mysql
    container_name: mysql-container
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
