version: '3.8'

services:
  app-backend:
    build: .
    container_name: app-backend-container
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    stdin_open: true
    tty: true

#  app-frontend: # Nowy kontener dla frontendu
#    build: ../frontend # Może to być ścieżka do katalogu, w którym znajduje się konfiguracja frontendu
#    container_name: app-frontend-container
#    ports:
#      - "5173:5173" # Zakładając, że frontend działa na porcie 5173
#    stdin_open: true
#    tty: true

  mysql:
    image: mysql
    container_name: mysql-container
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
