name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
          cd backend
          ./sh_scripts/clean_containers.sh --remove-app --remove-mysql
          ./sh_scripts/build_containers.sh
          docker-compose up -d
          exit_status=$?  # Pobranie statusu wyjścia
          if [ $exit_status -eq 0 ]; then
            echo "Docker Compose ran successfully"
          else
            echo "Error running Docker Compose"
            exit 1  # Wymuszenie błędu w przypadku niepowodzenia polecenia
          fi
